# Setup
title:            SacArts4ALL
tagline:          'SacArts4ALL'
description:      ‘SacArts4ALL’
url:              'http://sacarts4all.org'
baseurl:          'http://sacarts4all.org'

author:
  name:           'SacArts4ALL'
  url:            https://twitter.com/

# Custom vars
version:          1.1 | May 2017

github:
  repo:           https://github.com/code4sac/sacarts4all
