# Setup
title:            SacArts4ALL
tagline:          'SacArts4ALL'
description:      ‘SacArts4ALL’
url:              'https://tedfitzpatrick.github.io/sacarts4ALL/'
baseurl:          'https://tedfitzpatrick.github.io/sacarts4ALL/'

author:
  name:           'SacArts4ALL'
  url:            https://twitter.com/

# Custom vars
version:          1.1 | May 2017

github:
  repo:           https://github.com/tedfitzpatrick/sacarts4ALL
